name: Check Secret

on: [push]

jobs:
  check_secret:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Validate secret
      run: echo "El valor del secreto es ${{ secrets.MY_SECRET }} y el de la varible ${{ variables.MY_VAR }}"
