name: Check Secret

on: [push]

jobs:
  check_secret:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Validate secret
      run: |
        if [[ "${{ secrets.MY_SECRET }}" == "${{ vars.MY_VAR }}" ]]; then
          echo "El valor del secreto es válido: ${{ secrets.MY_SECRET }}"
        else
          echo "El valor del secreto es incorrecto"
        fi

        echo "El valor de la variable es: ${{ vars.MY_VAR }}"
